### ISSUE TITLE
This repo has too much useless commented code. Please remove it...

### ISSUE THREAD

**Issue by alisajidcs** [MajidAliKhanQuaid/vue-videoquizz#1]
https://github.com/MajidAliKhanQuaid/vue-videoquizz/blob/0d9e62f0dbaadf16e8e286d174a77d64dada063e/src/main.js#L14

https://github.com/MajidAliKhanQuaid/vue-videoquizz/blob/0d9e62f0dbaadf16e8e286d174a77d64dada063e/src/router/index.js#L17

**Comment by MajidAliKhanQuaid** [comment]
Please create a pull request for this, i'll review it
